/**
 * Apply a `ParsedAnki` to the local DB.
 *
 * Strategy: every Anki deck becomes one of our decks (1:1, name-mapped).
 * Card content is HTML-sanitized to plain Markdown before save. Reviews
 * are auto-generated by reviewStore.ensureReviewsForCard — the imported
 * cards become "new" in the FSRS sense, no inherited schedule.
 *
 * No de-dupe: re-importing the same .apkg adds duplicate decks. The UI
 * warns about this once we decide it matters.
 */

import { deckStore } from '../stores/decks.svelte';
import { cardStore } from '../stores/cards.svelte';
import { sanitizeAnkiHtml, type ParsedAnki } from './parse';

export interface ImportResult {
	decksCreated: number;
	cardsCreated: number;
	failed: number;
}

export async function importParsedAnki(parsed: ParsedAnki): Promise<ImportResult> {
	const result: ImportResult = { decksCreated: 0, cardsCreated: 0, failed: 0 };

	// Anki deck names use "::" as a separator for nesting — flatten with
	// a slash so the user sees a meaningful single-line title and we
	// don't have to invent a hierarchy concept yet.
	const ankiIdToDeckId = new Map<string, string>();
	for (const ankiDeck of parsed.decks) {
		const title = ankiDeck.name.replace(/::/g, ' / ');
		const created = await deckStore.createDeck({ title, description: 'Aus Anki importiert' });
		if (!created) {
			result.failed++;
			continue;
		}
		ankiIdToDeckId.set(ankiDeck.ankiId, created.id);
		result.decksCreated++;
	}

	// Cards whose Anki deck wasn't in the parsed list (e.g. the implicit
	// "Default" deck Anki uses for orphans) get a fallback deck so we
	// don't drop any user content.
	const ensureFallbackDeck = (() => {
		let id: string | null = null;
		return async () => {
			if (id) return id;
			const created = await deckStore.createDeck({
				title: 'Anki-Import',
				description: 'Karten ohne explizites Quell-Deck',
			});
			if (created) {
				id = created.id;
				result.decksCreated++;
			}
			return id;
		};
	})();

	let orderByDeck = new Map<string, number>();
	for (const card of parsed.cards) {
		let targetDeckId = ankiIdToDeckId.get(card.ankiDeckId);
		if (!targetDeckId) {
			const fallback = await ensureFallbackDeck();
			if (!fallback) {
				result.failed++;
				continue;
			}
			targetDeckId = fallback;
		}

		const cleanFields: Record<string, string> = {};
		for (const [key, value] of Object.entries(card.fields)) {
			cleanFields[key] = sanitizeAnkiHtml(value);
		}

		const order = orderByDeck.get(targetDeckId) ?? 0;
		orderByDeck.set(targetDeckId, order + 1);

		const created = await cardStore.createCard(
			{ deckId: targetDeckId, type: card.type, fields: cleanFields },
			order
		);
		if (created) {
			result.cardsCreated++;
		} else {
			result.failed++;
		}
	}

	return result;
}
