/**
 * Apply a `ParsedAnki` to the local DB.
 *
 * Strategy: every Anki deck becomes one of our decks (1:1, name-mapped).
 * Card content is HTML-sanitized to plain Markdown / inline media tags
 * before save. Reviews are auto-generated by reviewStore.ensureReviewsForCard
 * — the imported cards become "new" in the FSRS sense, no inherited schedule.
 *
 * Media: every referenced file is uploaded to mana-media first; the
 * resulting URL replaces the original Anki filename in the field text.
 * Files referenced from no card are skipped — many Anki decks bundle
 * orphaned media that bloats the upload time.
 *
 * No de-dupe: re-importing the same .apkg adds duplicate decks. The UI
 * warns about this once we decide it matters.
 */

import { deckStore } from '../stores/decks.svelte';
import { cardStore } from '../stores/cards.svelte';
import { uploadCardMedia, MediaUploadError } from '../media/upload';
import { sanitizeAnkiHtml, type ParsedAnki } from './parse';

export interface ImportResult {
	decksCreated: number;
	cardsCreated: number;
	mediaUploaded: number;
	mediaFailed: number;
	failed: number;
}

export interface MediaProgress {
	uploaded: number;
	total: number;
}

const MEDIA_CONCURRENCY = 4;
// Anki's <img src="..."> always quotes; we also catch [sound:foo.mp3].
const IMG_RE = /<img\b[^>]*\bsrc=["']([^"']+)["']/gi;
const SOUND_RE = /\[sound:([^\]]+)\]/g;

function collectMediaRefs(parsed: ParsedAnki): Set<string> {
	const refs = new Set<string>();
	for (const card of parsed.cards) {
		for (const value of Object.values(card.fields)) {
			let m: RegExpExecArray | null;
			IMG_RE.lastIndex = 0;
			while ((m = IMG_RE.exec(value))) refs.add(m[1]);
			SOUND_RE.lastIndex = 0;
			while ((m = SOUND_RE.exec(value))) refs.add(m[1]);
		}
	}
	return refs;
}

async function uploadOne(
	filename: string,
	parsed: ParsedAnki
): Promise<{ filename: string; url: string | null }> {
	const entry = parsed.mediaByFilename.get(filename);
	if (!entry) return { filename, url: null };
	try {
		const blob = await entry.async('blob');
		const file = new File([blob], filename, { type: guessMime(filename) });
		const media = await uploadCardMedia(file);
		return { filename, url: media.url };
	} catch (e) {
		if (e instanceof MediaUploadError) {
			console.warn(`[anki] media upload failed: ${filename}`, e.message);
		} else {
			console.warn(`[anki] media upload failed: ${filename}`, e);
		}
		return { filename, url: null };
	}
}

function guessMime(filename: string): string {
	const ext = filename.split('.').pop()?.toLowerCase() ?? '';
	const map: Record<string, string> = {
		jpg: 'image/jpeg',
		jpeg: 'image/jpeg',
		png: 'image/png',
		gif: 'image/gif',
		webp: 'image/webp',
		svg: 'image/svg+xml',
		mp3: 'audio/mpeg',
		ogg: 'audio/ogg',
		oga: 'audio/ogg',
		wav: 'audio/wav',
		m4a: 'audio/mp4',
		mp4: 'video/mp4',
		webm: 'video/webm',
	};
	return map[ext] ?? 'application/octet-stream';
}

async function uploadAllMedia(
	parsed: ParsedAnki,
	onProgress?: (p: MediaProgress) => void
): Promise<{ urlByFilename: Map<string, string>; uploaded: number; failed: number }> {
	const referenced = [...collectMediaRefs(parsed)].filter((f) => parsed.mediaByFilename.has(f));
	const urlByFilename = new Map<string, string>();
	let uploaded = 0;
	let failed = 0;

	if (referenced.length === 0) {
		onProgress?.({ uploaded: 0, total: 0 });
		return { urlByFilename, uploaded, failed };
	}

	let nextIdx = 0;
	async function worker() {
		while (true) {
			const idx = nextIdx++;
			if (idx >= referenced.length) return;
			const result = await uploadOne(referenced[idx], parsed);
			if (result.url) {
				urlByFilename.set(result.filename, result.url);
				uploaded++;
			} else {
				failed++;
			}
			onProgress?.({ uploaded: uploaded + failed, total: referenced.length });
		}
	}

	await Promise.all(Array.from({ length: MEDIA_CONCURRENCY }, () => worker()));
	return { urlByFilename, uploaded, failed };
}

export async function importParsedAnki(
	parsed: ParsedAnki,
	opts: { onMediaProgress?: (p: MediaProgress) => void } = {}
): Promise<ImportResult> {
	const result: ImportResult = {
		decksCreated: 0,
		cardsCreated: 0,
		mediaUploaded: 0,
		mediaFailed: 0,
		failed: 0,
	};

	// 1) Media — upload before any cards so the field-text rewrite has
	// real URLs to point at. Empty in the no-media case.
	const { urlByFilename, uploaded, failed } = await uploadAllMedia(parsed, opts.onMediaProgress);
	result.mediaUploaded = uploaded;
	result.mediaFailed = failed;

	// 2) Decks — Anki "::" hierarchy flattened to " / ".
	const ankiIdToDeckId = new Map<string, string>();
	for (const ankiDeck of parsed.decks) {
		const title = ankiDeck.name.replace(/::/g, ' / ');
		const created = await deckStore.createDeck({ title, description: 'Aus Anki importiert' });
		if (!created) {
			result.failed++;
			continue;
		}
		ankiIdToDeckId.set(ankiDeck.ankiId, created.id);
		result.decksCreated++;
	}

	// Fallback deck for cards whose Anki deck wasn't in the parsed list
	// (the "Default" deck Anki uses for orphans, mostly).
	const ensureFallbackDeck = (() => {
		let id: string | null = null;
		return async () => {
			if (id) return id;
			const created = await deckStore.createDeck({
				title: 'Anki-Import',
				description: 'Karten ohne explizites Quell-Deck',
			});
			if (created) {
				id = created.id;
				result.decksCreated++;
			}
			return id;
		};
	})();

	// 3) Cards — sanitize each field with the media URL map.
	const orderByDeck = new Map<string, number>();
	for (const card of parsed.cards) {
		let targetDeckId = ankiIdToDeckId.get(card.ankiDeckId);
		if (!targetDeckId) {
			const fallback = await ensureFallbackDeck();
			if (!fallback) {
				result.failed++;
				continue;
			}
			targetDeckId = fallback;
		}

		const cleanFields: Record<string, string> = {};
		for (const [key, value] of Object.entries(card.fields)) {
			cleanFields[key] = sanitizeAnkiHtml(value, urlByFilename);
		}

		const order = orderByDeck.get(targetDeckId) ?? 0;
		orderByDeck.set(targetDeckId, order + 1);

		const created = await cardStore.createCard(
			{ deckId: targetDeckId, type: card.type, fields: cleanFields },
			order
		);
		if (created) {
			result.cardsCreated++;
		} else {
			result.failed++;
		}
	}

	return result;
}
